### ISSUE TITLE
A subtle question on Bottle usage?

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_yarp-rpc#1]
In `tutorial_yarp-rpc`, I added the following codes.

```c++
if(!port.read(cmd) )// wait for reading data
{
    yError() << "cannot read the input port"; // Wait until receive data
}
// prepare reply
response.clear();// clear the last value
response.addString("You said"); //
response.append(cmd);// apppend(); append the contenf of the given bottle to the current list.
// write reply
port.reply(response);
printf("%s", response.get(0).asString().c_str());
```

Almost things seem ok. But a subtle question is the double quotation mark (“) of You said. How to avoid this kind of symbol. It seems inevitable that when I only want to append a string You said rather than “You said” using .addString("You said").
The desired results should be You said rather than “you said”.

![image](https://user-images.githubusercontent.com/55526431/68925043-82a49f80-07c5-11ea-8982-96fa59268c37.png)

**Comment by pattacini** [comment]
No problem in this case, @YANGGANG1971, as it's just a matter of how the command line interpreter gets and display the string 👍
