### ISSUE TITLE
For RpcClient port, cannot it use port.read()?

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_yarp-rpc#2]
For the `rpc-client.cpp`  under the path `./tutorial_yarp-rpc/src/`, I added the following codes,

```c++
if(port.read(cmd)){
printf("%d", ct);
ct ++;
yInfo()<<"Got response: you said";
port.reply(cmd);
printf("%s", cmd.get(0).asString().c_str());
}
else
{
yError() << "cannot read the input port";
}
}
```

errors showed “cannot read from RpcClient /client”.

![image](https://user-images.githubusercontent.com/55526431/68927855-10838900-07cc-11ea-95ac-50f20fab7b3e.png)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

`RpcClient` is a [Specialized RPC port][1] and, as such, it cannot be employed along with the `read()` service. My warm recommendation is to peruse the [YARP Tutorials][2] first, and only then try out VVV tutorials.

[1]: http://www.yarp.it/rpc_ports.html
[2]: http://www.yarp.it/tutorials.html

**Comment by YANGGANG1971** [comment]
Thanks for the warm recommendation. After reading the tutorials, it seems that I get the correct result as follows. Maybe I misunderstood the class description of [yarp::os::RpcClient](http://www.yarp.it/classyarp_1_1os_1_1RpcClient.html) before. It demonstrated that [read()](http://www.yarp.it/classyarp_1_1os_1_1RpcClient.html#ac68777d6f47c57835d9d92ae858f7f0b) can be used.   

![image](https://user-images.githubusercontent.com/55526431/68994207-a9490000-08c3-11ea-98c9-616e9d114010.png)

![image](https://user-images.githubusercontent.com/55526431/68994212-ba920c80-08c3-11ea-8fba-7e78246ddc1e.png)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

The way a RpcClient is intended to be used is described in [this page][1] of the official YARP documentation. Let me copy and paste hereinafter the relevant snippet:

```c++
#include <yarp/os/all.h>
#include <stdio.h>
using namespace yarp::os;
int main(int argc, char *argv[]) {
    if (argc<3) {
        fprintf(stderr, "Please supply (1) a port name for the client\n");
        fprintf(stderr, "              (2) a port name for the server\n");
        return 1;
    }
    Network yarp;
    const char *client_name = argv[1];
    const char *server_name = argv[2];
    RpcClient port;
    port.open(client_name);
    int ct = 0;
    while (true) {
    if (port.getOutputCount()==0) {
      printf("Trying to connect to %s\n", server_name);
      yarp.connect(client_name,server_name);
    } else {
      Bottle cmd;
      cmd.addString("COUNT");
      cmd.addInt32(ct);
      ct++;
      printf("Sending message... %s\n", cmd.toString().c_str());
      Bottle response;
      port.write(cmd,response);
      printf("Got response: %s\n", response.toString().c_str());
    }
    Time::delay(1);
    }
}
```

As you can see, the correct service you ought to use is [`RpcClient::write(cmd,response)`][2], which is in turn inherited from the class `yarp::os::AbstractContactable`.

Hope this helps.

[1]: http://www.yarp.it/rpc_ports.html
[2]: http://www.yarp.it/classyarp_1_1os_1_1AbstractContactable.html#a42a166b730265667ecdf56f1f8156d62
